// src/lib/components/Taskbar.svelte
<script lang="ts">
    import linkedinIcon from "$lib/assets/linkedin.svg";
    import githubIcon from "$lib/assets/github.svg";
    import emailIcon from "$lib/assets/email.svg";

    const socials = [
        {
            name: "LinkedIn",
            url: "https://linkedin.com/in/subasicantonio",
            icon: linkedinIcon,
        },
        {
            name: "GitHub",
            url: "https://github.com/antoniosubasic",
            icon: githubIcon,
        },
        {
            name: "Email",
            url: "mailto:antonio.subasic.public@gmail.com",
            icon: emailIcon,
        },
    ];
</script>

<div
    class="taskbar bg-white dark:bg-black text-black dark:text-white fixed bottom-5 left-0 z-10 w-full flex justify-center p-3 md:p-4"
>
    <div
        class="border rounded-full border-neutral-400 dark:border-neutral-600 flex items-center justify-center gap-8 md:gap-10 p-4 px-6"
    >
        {#each socials as social}
            <a
                href={social.url}
                target="_blank"
                rel="noopener noreferrer"
                class="hover:opacity-70 transition-opacity"
            >
                <img
                    src={social.icon}
                    alt="{social.name} icon"
                    class="w-7 h-7 xl:w-8 xl:h-8 dark:invert"
                />
            </a>
        {/each}
    </div>
</div>

// src/components/Taskbar.vue
<script setup lang="ts">
import linkedinIcon from '@/assets/linkedin.svg';
import githubIcon from '@/assets/github.svg';
import emailIcon from '@/assets/email.svg';

defineProps<{
  linkedin: string,
  github: string,
  email: string,
}>();
</script>

<template>
  <div class="wrapper">
    <div class="taskbar">
      <a :href="`https://www.linkedin.com/in/${linkedin}`" target="_blank" rel="noopener">
        <img :src="linkedinIcon" alt="LinkedIn" />
      </a>
      <a :href="`https://github.com/${github}`" target="_blank" rel="noopener">
        <img :src="githubIcon" alt="GitHub" />
      </a>
      <a :href="`mailto:${email}`">
        <img :src="emailIcon" alt="E-Mail" />
      </a>
    </div>
  </div>
</template>

<style scoped>
.wrapper {
  position: fixed;
  bottom: 3.75%;
  left: 0;
  right: 0;
  display: flex;
  justify-content: center;
}

.taskbar {
  display: flex;
  gap: 2rem;
  padding: 12px;
  border-radius: 15px;
  box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.15);
}

.taskbar a {
  display: flex;
  justify-content: center;
}

.taskbar img {
  width: 35px;
  height: 35px;
  object-fit: cover;
}

@media (prefers-color-scheme: dark) {
  .taskbar {
    box-shadow: 0 0 0 1px rgba(255, 255, 255, 0.15);
  }

  .taskbar img {
    filter: invert(1);
  }
}

@media screen and (max-height: 575px), screen and (max-width: 500px) {
  .taskbar {
    border-radius: 10px;
    padding: 9px;
  }

  .taskbar img {
    width: 30px;
    height: 30px;
  }
}

@media screen and (max-height: 440px) {
  .wrapper {
    display: none;
  }
}
</style>
